### ISSUE TITLE
註冊頁面出現錯誤

### ISSUE THREAD

**Issue by foxhsiao** [foodbank/bootcamp-gitflow#2]
![image](https://cloud.githubusercontent.com/assets/1214758/20337393/d68eadac-ac0b-11e6-8b0c-ab6da40f6d40.png)

後端噴 Error 500 ...12#@#

可能要麻煩 @foodbank/rd 確認一下問題

**Comment by JamesKai** [comment]
確認問題中～～

**Comment by foxhsiao** [comment]
我在 #1 發現可以直接修繕完成
